#define MACHINE_NAME_SIZE 40
#define FILE_NAME_SIZE 80
#define SECRET_KEY_SIZE 4
#define REQUEST_TYPE_SIZE 4
#define STATUS_SIZE 4
#define MAX_NUM_BYTES_IN_FILE 4
#define MAX_FILE_SIZE 100000
#define MAX_NUM_FILES 100
